version: '3.7'

services:

  backend:
    build:
      context: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/backend/.env  # Path to the .env file containing the environment variables for Django
    
  frontend:
    build:
      context: ./frontend
    container_name: nuxt_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
      - "24678:24678"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
